services:
  mysql:
    image: mysql:8.0
    container_name: frota_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frota_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - frota_network

  backend:
    build: .
    depends_on:
      - mysql
    container_name: frota_backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: frota_db

    volumes:
      - ./src:/app/src # Monta o código fonte no container
    command: npm run dev # Roda o projeto em modo de desenvolvimento

    networks:
      - frota_network

volumes:
  mysql_data:


networks:
  frota_network:
    driver: bridge
