services:
  db:
    image: mysql:8.0
    container_name: frota_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frota_db
      MYSQL_USER: root
      MYSQL_INITDB_SKIP_TZINFO: "1"
    command: --innodb-force-recovery=4
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - frota_network

  backend:
    build: .
    container_name: frota_backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306

    volumes:
      - ./src:/app/src # Monta o código fonte no container
    command: npm run dev # Roda o projeto em modo de desenvolvimento
    depends_on:
      - db
    networks:
      - frota_network

volumes:
  mysql_data:


networks:
  frota_network:
    driver: bridge
