name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 
          cache: 'npm'

      - name: Instalar dependências
        run: npm install 

      - name: Verificar instalação do Jest
        run: npx jest --version  # Verifica se o Jest está instalado corretamente

      - name: Configurar variáveis de ambiente
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Rodar testes
        run: npm test
